services:
  - type: web
    name: sm-insight-board
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard:server --bind 0.0.0.0:$PORT
    healthCheckPath: /health
